version: '3.4'

x-common-variables: &common-variables
  MYSQL_USER: wfs
  MYSQL_PASSWORD: wfs
  MYSQL_DATABASE: analytics
  MYSQL_ROOT_PASSWORD: password
  
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
    ports:
      - '3306:3306'
    restart: unless-stopped
    expose:
      - '3306'
    volumes:
      - ./analytics.sql:/docker-entrypoint-initdb.d/analytics.sql
  wfs-server:
    depends_on:
      - db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    links:
      - db
    restart: unless-stopped